import './globals.css'
import React, { ReactNode } from 'react'
import { HeaderComponent } from '@/src/components/header/HeaderComponent'
import { FooterComponent } from '@/src/components/footer/FooterComponent'
import ReactQueryWrapper from '@/app/ReactQueryWrapper'

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export interface IRootLayout {
    children: ReactNode
}

const RootLayout: React.FC<IRootLayout> = ({ children }: IRootLayout) => {
    return (
        <html lang="en">
            <head>
                <title>Maroon-shop</title>
            </head>
            <ReactQueryWrapper>
                <body>
                    <HeaderComponent />
                    <main>{children}</main>
                    <FooterComponent />
                </body>
            </ReactQueryWrapper>
        </html>
    )
}

export default RootLayout
